/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/penguine.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2, 0]}>
        <mesh geometry={nodes.mesh.geometry} material={materials['artic blue']} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials['eye yellow']} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials['eye red']} />
      </group>
    </group>
  )
}

useGLTF.preload('/penguine.gltf')
